apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-binding
subjects:
  - kind: ServiceAccount
    name: argo-workflow
    namespace: argo
roleRef:
  kind: ClusterRole
  name: argo-workflows
  apiGroup: rbac.authorization.k8s.io

