apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: argo-workflows-role
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflowtaskresults
      - workflowtasksets
      - cronworkflows
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: argo
  name: argo-workflows-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argo
roleRef:
  kind: Role
  name: argo-workflows-role
  apiGroup: rbac.authorization.k8s.io

