apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-build-
spec:
  entrypoint: kaniko
  volumes:
  - name: kaniko-secret
    projected:
      sources:
      - secret:
          name: docker-creds
          items:
          - key: username
            path: .dockerconfigjson
  templates:
  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace
        - --destination=k3d-demo-dev-cluster-registry:5000/myapp:latest
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    inputs:
      artifacts:
      - name: source
        path: /workspace

