apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-build-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/life1code/gitops-build-workflows.git'
    targetRevision: main
    path: workflows
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

