apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: maven-build
  namespace: argo
spec:
  serviceAccountName: build-sa
  entrypoint: maven-build
  templates:
  - name: maven-build
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: build-package
          template: maven-package
      - - name: upload-artifact
          template: upload-s3

  - name: git-clone
    container:
      image: alpine/git:latest
      command: ["git", "clone", "https://github.com/life1code/gitops-build-workflows.git", "/src"]

  - name: maven-package
    container:
      image: maven:3.8.4-openjdk-17
      command: ["/bin/sh", "-c"]
      args:
        - |
          cd /src
          mvn clean package -DskipTests
          cp target/*.jar /tmp/artifact.jar

  - name: upload-s3
    container:
      image: amazon/aws-cli:2.12.0
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access_key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret_key
      command: ["/bin/sh", "-c"]
      args:
        - aws s3 cp /tmp/artifact.jar s3://my-build-artifacts/your-app/{{workflow.uid}}/artifact.jar

